version: 0.2
env:
  secrets-manager:
    github_username: /CodeBuild/github_creds:username
    github_password: /CodeBuild/github_creds:password
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - touch .npmignore
      - npm install -g gatsby
      - npm install --save gatsby-plugin-twitter
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - gatsby build --prefix-paths
  post_build:
    commands:
      - mkdir /temp
      - git clone https://github.com/xRokco/Rokco.org.git /temp/site
      - cp -r public/* /temp/site/blog/
      - cd /temp/site
      - git add .
      - git commit -m "adding new blog post"
      - git push https://$github_username:$github_password@github.com/xRokco/Rokco.org.git
