version: 0.2
env:
  secrets-manager:
    github_username: /CodeBuild/github_creds:username
    github_password: /CodeBuild/github_creds:password
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install -g gatsby@latest
      - npm install
      - npm install typography react-typography react react-dom gatsby-plugin-twitter
      - gatsby build --prefix-paths
      - mkdir /temp
      - git clone https://github.com/xRokco/Rokco.org.git /temp/site
      - cp -r public/* /temp/site/blog/
      - cd /temp/site
      - git add .
      - git config --global user.email "matt@rokco.org"
      - git config --global user.name "Matt Carrick"
      - git commit -m "adding new blog post"
      - git push https://$github_username:$github_password@github.com/xRokco/Rokco.org.git
