version: 0.2
phases:
  install:
    commands:
      - touch .npmignore
      - npm install -g gatsby
      - npm install --save gatsby-plugin-twitter
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "public/**/*"
    - .ebextensions/**/*